### PR TITLE
Set og-image for share preview

### LINKED ISSUE #58: Set og-image for share preview
The URL to image for social networks is currently broken. It is easy to fix this, but you need a suitable image of 1200x630 size.

https://github.com/mirumee/saleor-docs/blob/1a8c7934efbf932f5c0473b2b0be8f2298398d30/website/siteConfig.js#L117-L118

### PR DESCRIPTION
**Pull request by dylmye**
This PR closes #58. The image is provisional, I'm happy to update it with one provided by your team. I'm also happy to test the website using a validator if you wish.

### CODE REVIEW

**Comment by dylmye** [comment]
are we good to merge? :)

**Comment by maarcingebala** [comment]
Thanks for making the effort! Here is the image that we should use:

docs

**Comment by maarcingebala** [comment]
@dylmye Let me know if you have time to change it to use the new image. I would name the file something like `og-image.png` simply.

**Comment by dylmye** [comment]
Sure thing, I'll sort this out by the end of day :)

**Comment by maarcingebala** [comment]
Perfect, thanks a lot!

**Comment by maarcingebala** [comment]
Thank you for contributing to Saleor! 🎉

**Pull request merged**
