### PR TITLE
Store payment source

### PR DESCRIPTION
**Pull request by mateuszgrzyb**
[SALEOR-4246](https://app.clickup.com/t/wkwvfd)

### CODE REVIEW

**Review by krzysztofwolski — CHANGES_REQUESTED** [review]
package-lock.json should not be updated in this PR. Seems you are using a different npm version than currently used in the project.

**Comment by patrys** [comment]
Task linked: [SALEOR-4246 Update Saleor's documentation](https://app.clickup.com/t/2549495/SALEOR-4246)

**Review by krzysztofwolski — APPROVED** [review]

**Comment by krzysztofwolski** [comment]
@mateuszgrzyb in the future please push directly to this repo, not fork. I don't have access rights to the forked repos and cannot rebase by myself. 

https://github.com/mirumee/saleor-docs/pull/322
this PR contains rebased version of this PR

**Comment by patrys** [comment]
@krzysztofwolski Only team members can push to this repository and you _do_ have access to branches submitted as PRs unless the submitter explicitly disabled that.

**Comment by krzysztofwolski** [comment]
Sorry, thought Mateusz has such access.
Was not able to push rebased code to the fork, that's why I introduced new PR

**Pull request closed without merging**
